server:
  port: 3031

spring:
  datasource:
    username: root
    password: Am@n2515
    url: jdbc:mysql://localhost:3306/easyStay_hotel_db
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
    max-file-size: 5MB
    max-request-size: 5MB
    file-size-threshold: 2KB

